name: Download CSV File
on:
  push:
    branches: [ master ]
jobs:
  download-csv-file:
    runs-on: ubuntu-latest
    steps:
      - name: List dir
        run: ls -l
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: List dir
        run: ls -l
      - name: Download the csv file
        uses: suisei-cn/actions-download-file@v1
        id: downloadfile  # Remember to give an ID if you need the output filename
        with:
          url: ${{ secrets.SHEET_URL }}
          target: public/
      - name: List dir
        run: ls -l
      - name: Rename the file
        run: mv public/pub public/sheet.csv && ls -l public/
      - name: Read CSV
        id: csv
        uses: juliangruber/read-file-action@v1
        with:
          path: ./public/sheet.csv
      - name: Convert to Markdown Table
        uses: petems/csv-to-md-table-action@master
        id: csv-table-output
        with:
          csvinput: ${{ steps.csv.outputs.content }}
      - name: List dir
        run: ls -l public/
      - uses: stefanzweifel/git-auto-commit-action@v4
