name: Download CSV File
on:
  push:
    branches: [ master ]
jobs:
  download-csv-file:
    runs-on: ubuntu-latest
    steps:
      - name: Download the file
        uses: suisei-cn/actions-download-file@v1
        id: downloadfile  # Remember to give an ID if you need the output filename
        
        with:
          url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vS86M3ph2VgiOvYdCnIB8lDFmTc_SnSQ6AOSMXGWdv6QTnnK_NDCeU0FE5qg_7B3wDNvctWVg6KecLF/pub?gid=0&single=true&output=csv"
          target: public/
      - name: convert to csv
        run: mv public/pub public/sheet.csv && ls -l public/
