name: Read CSV
on:
  push:
    branches: [ master ]

  schedule:
    - cron:  '15 07 * * 1,4' # Runs at 20:15 UTC on Mo and Th
    
jobs:
  download-csv-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout into repository
        uses: actions/checkout@master
        with:
          ref: "master"
         
      - name: Remove README
        run: rm README.md && ls -l
        
      - name: Download the csv file from google sheets url
        uses: suisei-cn/actions-download-file@v1
        id: downloadfile  # Remember to give an ID if you need the output filename
        with:
          url: ${{ secrets.SHEET_URL }}
          target: public/

      - name: Rename the downloaded file
        run: mv public/pub public/sheet.csv && ls -l public/
        
      - name: Create datetime.md
        run: date +"%d. %B %Y %X %Z" >> public/datetime.md && ls -l public/
        
      - name: Read CSV
        id: csv
        uses: juliangruber/read-file-action@v1
        with:
          path: ./public/sheet.csv
        
      - name: Convert CSV to Markdown
        uses: petems/csv-to-md-table-action@master
        id: csv-table-output
        with:
          csvinput: ${{ steps.csv.outputs.content }}
        
      - name: Write markdown
        run: echo "${{steps.csv-table-output.outputs.markdown-table}}" >> public/sheet.md && ls -l public/
        
      - name: Copy the readme-template.md to the root dir
        run: scp templates/readme-template.md ./  && ls -l
      
      - name: Rename readme-template to README
        run: mv readme-template.md README.md && ls -l
        
      - name: "Dynamic Template Render"
        uses: varunsridharan/action-dynamic-readme@main
        with: 
          files: |
            ./README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  
      #- name: Commit changes
      #  uses: stefanzweifel/git-auto-commit-action@v4
